language: elixir
sudo: required

elixir:
  - 1.8
  - 1.11
otp_release:
  - 21.0
  - 23.0

before_script:
  - make pull_deps
  - make linter
script:
  - make unit_test
after_script:
  - make docs_report
after_success:
  - bash <(curl -s https://codecov.io/bash)
